### ISSUE TITLE
Busybox as image for examples.

### ISSUE THREAD

**Issue by mstrello** [PacktPublishing/Cloud-Native-with-Kubernetes#2]
Hello! I'm having some issues trying the exercises in Chapter4. For instance, in Section "Controlling Deployments" the manifest for the deployment uses busybox as image for the sample containers. But, without a command each container exits inmediately and Kubernetes restarts it again and again, because the restartPolicy is Always by default.

 I'm using nginx as my image and I can follow the examples, but I'm not sure if I'm doing something wrong with original sample using busybox, because busybox is being used for most of the examples.

Thanks in advance for your support.

**Comment by zihaoyu** [comment]
I agree. I think we should change the docker image to nginx or something that runs forever.
